version: '2'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 8080:80
  database:
    image: mysql:5.7.7
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USERNAME=homestead"
    ports:
    - "33061:3306"